Feature/add polly
Gh0stF1ghter/Rent-n-Ride-RentService pull request #10
Opened 2024-07-05 11:42 UTC by Gh0stF1ghter

2024-07-08 13:08 UTC, 5Ka-me requested changes

2024-07-08 13:08 UTC, 5Ka-me commented on Rent.BusinessLogic/Exceptions/ExceptionMessages/ExceptionMessages.cs
> +        "Something went wrong during request: " + connection;
Use interpolation as you did above

2024-07-08 13:08 UTC, 5Ka-me commented on Rent.BusinessLogic/Services/Implementations/VehicleClientHistoryService.cs
>      {
Split this method. It's too big

2024-07-08 13:08 UTC, 5Ka-me commented on Rent.BusinessLogic/Services/Implementations/VehicleClientHistoryService.cs
> +            await ProcessExceptionAsync(userResponse, _userServiceConnection, cancellationToken);
Don't you think it is not a good flow to add and remove data?
What if removing data will fail?
Maybe require another approach

2024-07-08 15:11 UTC, 5Ka-me approved these changes

2024-07-10 07:18 UTC, MaliyOna approved these changes

2024-07-10 07:41 UTC, merged